### ISSUE TITLE
Doubts regarding BloodVault app using android

### ISSUE THREAD

**Issue by Jebastin215** [jayeshpatil665/bloodvault_android#1]
it's working but when i register and use the registered details to login the app gets automatically exits. I also want to know where the data gets stored. I also want the login details as a admin. Please help me with that

**Comment by jayeshpatil665** [comment]
Yes, Jebastin I address this issue printout by you. 
You are facing this issue because our API server is down. 
This issue will persist for now, I will need to redeploy our backend APIs in order to make APK work.
Update : 
Hi, Jebastin . I added link to Google Drive in Readme file for APK/DB/API's . You can download it from there.

**Comment by Jebastin215** [comment]
When will you do that ?

**Comment by peaciva** [comment]
can you provide the code for the API? I can host it myself.

**Comment by jayeshpatil665** [comment]
Hi, @peaciva . I added link to Google Drive in Readme file for APK/DB/API's . You can download it from there.
